theme = "gruber-darker"

[editor]
line-number = "relative"
auto-completion = true
path-completion = true
completion-timeout = 250

[keys.normal]
C-i = "completion"

[editor.clipboard-provider.custom]
yank = { command = "win32yank.exe", args = ["-i", "--crlf"] }
paste = { command = "win32yank.exe", args = ["-o", "--lf"] }
primary-yank = { command = "win32yank.exe", args = ["-i", "--crlf"] }
primary-paste = { command = "win32yank.exe", args = ["-o", "--lf"] }
